# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gus Oberdick
email: go125412@ohio.edu
description: > # this means to ignore newlines until "baseurl:"
  Hello World! My name is gus oberdick and I love to program 
  websites. I am a CS student at Ohio University and have
  experience with a multitude of programming languages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gusoberdick.com" # the base hostname & protocol for your site
twitter_username: gustavo
github_username:  guso133

sass:
    sass_dir: assets/css
    style: compressed

# Build settings
markdown: kramdown
